version: '3.8'

name: 'axum-rest-api'

services:
  db:
    container_name: axum-rest-api-db
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=axum-rest-api
      - MONGO_INITDB_USERNAME=admin
      - MONGO_INITDB_PASSWORD=1234